In [1]:
import numpy as np
import laspy as lp
import pandas as pd
import trimesh
from plyfile import PlyData, PlyElement, PlyProperty

In [77]:
point_cloud2=lp.read("DALES POINT NET Trainning/data/dales_las/train/5085_54320.las")
point_data2 = np.stack([point_cloud2.X, point_cloud2.Y, point_cloud2.Z, point_cloud2.classification], axis=0).transpose((1, 0))


In [78]:
point_cloud=lp.read("DALES POINT NET Trainning/data/dales_las/train/5080_54435.las")
point_data = np.stack([point_cloud.X, point_cloud.Y, point_cloud.Z, point_cloud.classification], axis=0).transpose((1, 0))


In [79]:
df = pd.DataFrame(data=point_data, columns=['X','Y','Z','Class'])
df

X          Y      Z  Class
0         50800157  544350043   9432      1
1         50800263  544350019   9429      1
2         50800052  544350073   9432      1
3         50800107  544350060   9428      1
4         50800310  544350072   9425      1
...            ...        ...    ...    ...
11345686  50850001  544364092   9343      1
11345687  50850000  544362143  11274      2
11345688  50850000  544376573   9458      2
11345689  50850001  544375494   9424      1
11345690  50850000  544368722   9359      1

[11345691 rows x 4 columns]

In [80]:
df2 = pd.DataFrame(data=point_data2, columns=['X','Y','Z','Class'])
df2

X          Y     Z  Class
0         50850112  543202258  -105      1
1         50850228  543202161  -112      1
2         50850249  543202222  -106      1
3         50850529  543202151  -113      1
4         50850084  543202194  -111      1
...            ...        ...   ...    ...
14394744  50895026  543200700  4683      2
14394745  50895019  543200479  4665      2
14394746  50895055  543200045  4637      2
14394747  50895036  543200116  4502      2
14394748  50895078  543200974  4637      2

[14394749 rows x 4 columns]

In [81]:
X_std = (df.X - df.X.min()) / (df.X.max() - df.X.min())
X_scaled = X_std * (df.X.max() - df.X.min()) + df.X.min()
X_std


0           0.003160
1           0.005279
2           0.001060
3           0.002160
4           0.006219
              ...   
11345686    0.999940
11345687    0.999920
11345688    0.999920
11345689    0.999940
11345690    0.999920
Name: X, Length: 11345691, dtype: float64

In [82]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler(feature_range=(250.024994, 750.075012))
scaler_y = MinMaxScaler(feature_range=(250.020004, 750.059998))
scaler_z = MinMaxScaler(feature_range=(24.190001, 72.570000))


In [83]:
scaler_x.fit_transform(df[['X', 'Class']])

array([[251.60499406, 312.53124625],
       [252.66499409, 312.53124625],
       [250.55499402, 312.53124625],
       ...,
       [750.035012  , 375.0374985 ],
       [750.045012  , 312.53124625],
       [750.035012  , 312.53124625]])

In [84]:
scaler_y.fit_transform(df[['Y', 'Class']])

array([[250.47000399, 312.52500325],
       [250.230004  , 312.52500325],
       [250.77000399, 312.52500325],
       ...,
       [515.77000081, 375.0300025 ],
       [504.98000094, 312.52500325],
       [437.26000175, 312.52500325]])

In [99]:
scaler_z.fit_transform(df[['Z', 'Class']])

array([[38.9000007 , 30.23750087],
       [38.8700007 , 30.23750087],
       [38.9000007 , 30.23750087],
       ...,
       [39.16000069, 36.28500075],
       [38.8200007 , 30.23750087],
       [38.17000071, 30.23750087]])

In [86]:
df.X.max() - df.X.min()

50005

In [87]:
df.Y.max() - df.Y.min()

50004

In [88]:
df.Z.max() - df.Z.min()

4838

In [89]:
df2.Z.max() - df2.Z.min()

9060

In [90]:
(df2.Z.max() - df2.Z.min()) / (df.Z.max() - df.Z.min())

1.8726746589499794

In [91]:
24.190001 * 1.8726746589499794

45.300001872674656

In [92]:
72.570000 * 1.8726746589499794

135.9

In [93]:
0.33545768538 / 0.0049746293901104365

67.4337039150876

In [94]:
plydata = PlyData.read('DALES POINT NET Trainning/data/dales_ply/train/5080_54435.ply')
point_data_ply = np.stack([plydata['vertex']['x'], plydata['vertex']['y'], plydata['vertex']['z'], plydata['vertex']['reflectance']], axis=0).transpose((1, 0))
df1 = pd.DataFrame(data=point_data_ply, columns=['X','Y','Z','reflectance'])
df1

X           Y          Z  reflectance
0         251.604996  250.470001  38.900002          0.0
1         252.664993  250.229996  38.869999          0.0
2         250.554993  250.770004  38.900002          0.0
3         251.104996  250.639999  38.860001          0.0
4         253.134995  250.759995  38.830002          0.0
...              ...         ...        ...          ...
11345686  750.044983  390.959991  38.009998          0.0
11345687  750.034973  371.470001  57.320000          0.0
11345688  750.034973  515.770020  39.160000          0.0
11345689  750.044983  504.980011  38.820000          0.0
11345690  750.034973  437.260010  38.169998          0.0

[11345691 rows x 4 columns]

In [97]:
df1.max()

X              750.075012
Y              750.059998
Z               72.570000
reflectance      0.000000
dtype: float32

In [98]:
df1.min()

X              250.024994
Y              250.020004
Z               24.190001
reflectance      0.000000
dtype: float32